//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcrGenerator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1031")]
        public string Location {
            get {
                return ((string)(this["Location"]));
            }
            set {
                this["Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://fihel2suas150.groupad1.com:8983/solr/matcher_payments_se/update/json/docs?" +
            "commit=true")]
        public string Solr {
            get {
                return ((string)(this["Solr"]));
            }
            set {
                this["Solr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"Name\":\"Test\",\"Url\":\"http://fihel2stas143.groupad1.com:8983/solr/matcher_paymen" +
            "ts_{0}/update/json/docs?commit=true\"},{\"Name\":\"UAT\",\"Url\":\"http://fihel2suas150." +
            "groupad1.com:8983/solr/matcher_payments_{0}/update/json/docs?commit=true\"}]")]
        public string Environments {
            get {
                return ((string)(this["Environments"]));
            }
            set {
                this["Environments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"Name\":\"se\"},{\"Name\":\"fi\"}]")]
        public string Indexes {
            get {
                return ((string)(this["Indexes"]));
            }
            set {
                this["Indexes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedEnvironment {
            get {
                return ((string)(this["SelectedEnvironment"]));
            }
            set {
                this["SelectedEnvironment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedIndex {
            get {
                return ((string)(this["SelectedIndex"]));
            }
            set {
                this["SelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"Name\":\"ocr\",\"Type\":1,\"Length\":10,\"Prefix\":\"7008\",\"Value\":\"\"},{\"Name\":\"case\",\"T" +
            "ype\":1,\"Length\":7,\"Prefix\":null,\"Value\":\"\"},{\"Name\":\"debtor\",\"Type\":0,\"Length\":2" +
            "0,\"Prefix\":null,\"Value\":\"\"}]")]
        public string Fields {
            get {
                return ((string)(this["Fields"]));
            }
            set {
                this["Fields"] = value;
            }
        }
    }
}
